### ISSUE TITLE
Variable Gutter Please!

### ISSUE THREAD

**Issue by miqueldespuig** [CLackyM/grid-image-generator#1]
Hey @CLackyM !

Awesome functional script, using it to apply columns and gutter to my PowerBI dashboards. Could you please add to option to select how much gutter you want?

The thing is in the grid available in the page design we can only snap to 8px spaces and to make a gutter of 8, 16, or 32px would be great!

Thanks a lot a great work!

**Comment by CLackyM** [comment]
done
